---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: lambda-irsa
  namespace: kgateway-system
spec:
  kube:
    serviceAccount:
      extraAnnotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/lambda-invoker-role
    envoyContainer:
      bootstrap:
        logLevel: debug
      image:
        # Locally built image that uses the 1.34.0-patch0 envoy-gloo tag.
        tag: v2.0.0-main
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http
  namespace: kgateway-system
  annotations:
    gateway.kgateway.dev/gateway-parameters-name: lambda-irsa
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-irsa
  namespace: httpbin
  labels:
    app: httpbin
spec:
  hostnames:
  - "www.example.com"
  parentRefs:
  - name: http
    namespace: kgateway-system
  rules:
  - matches:
    - path:
        type: Exact
        value: /lambda-irsa/1
    backendRefs:
    - name: lambda-irsa
      kind: Upstream
      group: gateway.kgateway.dev
      namespace: httpbin
      filters:
      - type: ExtensionRef
        extensionRef:
          group: gateway.kgateway.dev
          kind: Parameter
          name: tim-test
  - matches:
    - path:
        type: Exact
        value: /lambda-irsa/2
    backendRefs:
    - name: lambda-irsa
      kind: Upstream
      group: gateway.kgateway.dev
      namespace: httpbin
      filters:
      - type: ExtensionRef
        extensionRef:
          group: gateway.kgateway.dev
          kind: Parameter
          name: echo-test
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Upstream
metadata:
  name: lambda-irsa
  namespace: httpbin
spec:
  type: aws
  aws:
    region: us-east-1
    accountId: "000000000000"
    auth:
      roleARN: "arn:aws:iam::000000000000:role/lambda-invoker-role"
    endpointURL: "http://172.18.0.2:31566"
