---
apiVersion: v1
kind: Namespace
metadata:
  name: gwtest
  labels:
    developer: tim
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: http-gw
  namespace: gwtest
spec:
  kube:
    serviceAccount:
      extraAnnotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_ROLE_NAME}
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http-gw
  namespace: gwtest
  annotations:
    gateway.kgateway.dev/gateway-parameters-name: http-gw
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: lambda-route
  namespace: gwtest
spec:
  parentRefs:
    - name: http-gw
  hostnames:
  - www.example.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /lambda
      backendRefs:
        - name: lambda-backend
          kind: Backend
          group: gateway.kgateway.dev
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: lambda-backend
  namespace: gwtest
spec:
  type: AWS
  aws:
    accountId: "${AWS_ACCOUNT_ID}"
    lambda:
      functionName: "tim-test"
