kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http-gw
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: lambda-route
  namespace: gwtest
spec:
  parentRefs:
    - name: http-gw
  hostnames:
  - www.example.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /lambda
      backendRefs:
        - name: lambda-backend
          kind: Backend
          group: gateway.kgateway.dev
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: lambda-backend
  namespace: gwtest
spec:
  type: aws
  aws:
    # Note, no spec.aws.auth is specified, so the default AWS auth will be used.
    # If I have to manually add the right lambda roles to the node role to make this work.
    accountId: "${AWS_ACCOUNT_ID}"
    lambda:
      functionName: "tim-test"
